# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: '/acceptance_tests/app'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: '/acceptance_tests/tests/redis'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: '/acceptance_tests/tests'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: '/acceptance_tests/app'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
