inherits:
  - utils:base
  - utils:no-design-checks
  - utils:c2cwsgiutils
  - utils:fix
  - duplicated

ignore-paths:
  - docs
  - acceptance_tests
  - tests

pylint:
  options:
    extension-pkg-allow-list:
      - ujson
      - lxml

mypy:
  options:
    python-version: '3.11'

ruff:
  options:
    target-version: py311
  disable:
    - TD # Disable all TODO checks
    - FIX # Disable all FIXME checks
