inherits:
  - utils:base
  - utils:no-design-checks
  - utils:c2cwsgiutils
  - utils:fix
  - duplicated

ignore-paths:
  - docs
  - acceptance_tests
  - tests

pylint:
  options:
    extension-pkg-allow-list:
      - ujson
      - lxml

mypy:
  options:
    python_version: '3.10'
