inherits:
  - utils:base
  - utils:no-design-checks
  - utils:fix
  - duplicated

doc-warnings: true

ignore-paths:
  - docs
  - acceptance_tests
  - tests

pylint:
  options:
    extension-pkg-allow-list:
      - ujson
      - lxml
  disable:
    - no-else-return
    - no-else-raise
    - missing-module-docstring
    - missing-timeout # A default timeout is set

pydocstyle:
  disable:
    - D104 # Missing docstring in public package
    - D105 # Missing docstring in magic method
    - D107 # Missing docstring in __init__

pycodestyle:
  disable:
    # Buggy checks with Python 3.12
    - E221 # multiple spaces before operator
    - E702 # multiple statements on one line (semicolon)

bandit:
  options:
    config: .bandit.yaml
