strictness: veryhigh

ignore-paths:
  - docs
  - acceptance_tests
  - tests

pylint:
  disable:
    - global-statement
    - line-too-long
    - import-outside-toplevel
    - invalid-name
    - no-else-return
    - no-else-raise
    - no-self-use
    - import-error
    - superfluous-parens
    - too-few-public-methods
    - too-many-arguments
    - ungrouped-imports
    - unused-argument
    - use-symbolic-message-instead

pep8:
  options:
    max-line-length: 110
  disable:
    - E203

mypy:
  run: true

mccabe:
  run: false
