[tool.black]
line-length = 110
target-version = ['py38']

[tool.poetry]
name = "c2cwsgiutils"
version = "0.0.0"
description = "Common utilities for Camptocamp WSGI applications"
authors = ["Camptocamp <info@camptocamp.com>"]
