[tool.black]
line-length = 110
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 110

[tool.mypy]
python_version = 3.10
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict = true

[tool.poetry]
name = "c2cwsgiutils"
version = "0.1.0"
description = "Common utilities for Camptocamp WSGI applications"
readme = "README.md"
authors = ["Camptocamp <info@camptocamp.com>"]
keywords = ["geo", "gis", "sqlalchemy", "orm", "wsgi"]
repository = "https://github.com/camptocamp/c2cwsgiutils"
license = "BSD-2-Clause"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Plugins",
  "Framework :: Pyramid",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Intended Audience :: Information Technology",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
  "Typing :: Typed",
]
packages = [{ include = "c2cwsgiutils" }]
include = [
"c2cwsgiutils/py.typed",
"c2cwsgiutils/acceptance/screenshot.js",
"c2cwsgiutils/acceptance/package.json",
"c2cwsgiutils/acceptance/package-lock.json",
]

[tool.poetry.scripts]
c2cwsgiutils-genversion = "c2cwsgiutils.scripts.genversion:main"
c2cwsgiutils-coverage-report = "c2cwsgiutils.scripts.coverage_report:main"
c2cwsgiutils-stats-db = "c2cwsgiutils.scripts.stats_db:main"
c2cwsgiutils-test-print = "c2cwsgiutils.scripts.test_print:main"
c2cwsgiutils-check-es = "c2cwsgiutils.scripts.check_es:main"

[tool.poetry.plugins."plaster.loader_factory"]
c2c = "c2cwsgiutils.loader:Loader"
"c2c+ini" = "c2cwsgiutils.loader:Loader"
"c2c+egg" = "c2cwsgiutils.loader:Loader"

[tool.poetry.plugins."plaster.wsgi_loader_factory"]
c2c = "c2cwsgiutils.loader:Loader"
"c2c+ini" = "c2cwsgiutils.loader:Loader"
"c2c+egg" = "c2cwsgiutils.loader:Loader"

[tool.poetry.plugins."paste.filter_factory"]
client_info = "c2cwsgiutils.client_info:filter_factory"
sentry = "c2cwsgiutils.sentry:filter_factory"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
requests = { version = "2.31.0" }
pyyaml = { version = "6.0.1" }
alembic = { version = "1.12.1", optional = true }
boltons = { version = "23.0.0", optional = true }
cornice = { version = "6.0.1", optional = true }
redis = { version = "5.0.1", optional = true }
gunicorn = { version = "21.2.0", optional = true }
lxml = { version = "4.9.4", optional = true }
objgraph = { version = "3.6.0", optional = true }
psycopg2 = { version = "2.9.9", optional = true }
pyramid = { version = "2.0.2", optional = true }
pyramid-tm = { version = "2.5", optional = true }
sentry-sdk = { version = "1.31.0", optional = true }
ujson = { version = "5.8.0" }
cee_syslog_handler = { version = "0.6.0" }
SQLAlchemy = { version = "2.0.25", optional = true }
SQLAlchemy-Utils = { version = "0.41.1", optional = true }
"zope.interface" = { version = "6.0", optional = true }
"zope.sqlalchemy" = { version = "3.1", optional = true }
pyjwt = { version = "2.8.0", optional = true }
requests-oauthlib = { version = "1.3.1", optional = true }
waitress = { version = "2.1.2", optional = true }
scikit-image = { version = "0.21.0", optional = true }
certifi = { version = "2023.7.22", optional = true }
prometheus-client = { version = "0.17.1", optional = true}
pyramid_mako = { version = "1.1.0", optional = true}
pillow = { version = "10.0.1", optional = true }
scipy = { version = "1.10.1", optional = true }
urllib3 = "2.0.7"

[tool.poetry.extras]
standard = [
  # alembic
  "alembic",
  # oauth2
  "pyjwt",
  "requests-oauthlib",
  # sentry
  "sentry-sdk",
  # broadcast
  "redis",
  # webserver
  "cornice",
  "gunicorn",
  "psycopg2",
  "pyramid",
  "pyramid-tm",
  "SQLAlchemy",
  "SQLAlchemy-Utils",
  "zope.interface",
  "zope.sqlalchemy",
  "prometheus_client",
  "pyramid_mako",
]
alembic = ["alembic"]
debug = ["objgraph"]
oauth2 = ["pyjwt", "requests-oauthlib"]
sentry = ["sentry-sdk"]
dev = ["waitress"]
broadcast = ["redis"]
webserver = [
  "cornice",
  "gunicorn",
  "psycopg2",
  "pyramid",
  "pyramid-tm",
  "SQLAlchemy",
  "SQLAlchemy-Utils",
  "zope.interface",
  "zope.sqlalchemy",
  "prometheus_client",
  "pyramid_mako"]
tests = ["lxml", "boltons"]
all = [
  # alembic
  "alembic",
  # debug
  "objgraph",
  # oauth2
  "pyjwt",
  "requests-oauthlib",
  # sentry
  "sentry-sdk",
  # dev
  "waitress",
  # broadcast
  "redis",
  # webserver
  "cornice",
  "gunicorn",
  "psycopg2",
  "pyramid",
  "pyramid-tm",
  "SQLAlchemy",
  "SQLAlchemy-Utils",
  "zope.interface",
  "zope.sqlalchemy",
  "prometheus_client",
  "pyramid_mako",
  # tests
  "lxml",
  "boltons",
]
test_images = ["scikit-image"]

[tool.poetry.dev-dependencies]
# pylint = { version = "2.15.6" }
prospector = { extras = ["with_bandit", "with_mypy", "with_pyroma"], version = "1.10.3" }
coverage = "7.3.4"
junit2html = "30.1.3"
pytest = "7.4.4"
pytest-cov = "4.1.0"
pytest-html = "4.0.2"
types-pyyaml = "6.0.12.12"
types-requests = "2.31.0.20240106"
types-redis = "4.6.0.20240106"
types-ujson = "5.8.0.1"
types-python-dateutil = "2.8.19.20240106"
typing_extensions = "4.8.0"

[tool.poetry.group.dev.dependencies]
prospector-profile-duplicated = "0.3.0"

[build-system]
requires = [
  "poetry-core>=1.0.0",
  "poetry-dynamic-versioning[plugin]",
  "poetry-plugin-tweak-dependencies-version",
  "poetry-plugin-drop-python-upper-constraint"
]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern = "^(?P<base>\\d+(\\.\\d+)*)"
format-jinja = """
{%- if env.get("VERSION_TYPE") == "version_branch" -%}
{{serialize_pep440(bump_version(base, 0 if env.get("IS_MASTER") == "TRUE" else 2), dev=distance)}}
{%- elif distance == 0 -%}
{{serialize_pep440(base)}}
{%- else -%}
{{serialize_pep440(bump_version(base), dev=distance)}}
{%- endif -%}
"""

[tool.poetry-plugin-tweak-dependencies-version]
default = "present"
SQLAlchemy = ">=1.4.0,<3.0.0"
