#!/bin/bash
# Upgrade the DB
set -eu

# wait for the DB to be UP
while ! echo "import sqlalchemy; sqlalchemy.create_engine('${SQLALCHEMY_URL}').connect()" | python3 2> /dev/null; do
  echo "Waiting for the DB to be reachable"
  sleep 1
done

for ini in *alembic*.ini; do
  if [[ -f "${ini}" ]]; then
    echo "${ini} ==========================="
    echo History
    alembic -c "${ini}" history
    echo Head
    alembic -c "${ini}" heads
    echo Upgrade
    alembic -c "${ini}" upgrade head
    echo Current
    alembic -c "${ini}" current
    echo "==========================="
  fi
done
