#!/bin/bash
# Script used when building acceptance test images to install the docker tools needed to run them.
set -ex

apt-get update
apt-get install --yes --no-install-recommends docker-ce
python3 -m pip install docker-compose
apt-get clean
rm -r /var/lib/apt/lists/*
