#!/bin/bash -eux

tag=''

if [[ $1 =~ ^refs/tags/([0-9]+(\.[0-9]+)*)$ ]]
then
  tag="${BASH_REMATCH[1]}"
  echo "Create release ${tag} in pypi"
  summon --yaml '
    USERNAME: !var gs/ci/pypi/username
    PASSWORD: !var gs/ci/pypi/password
  ' bash -c "scripts/release '${tag}'"
  echo "Release tag ${tag}"
elif [[ $1 =~ ^refs/heads/(release_[0-9]+)$ ]]
then
  tag="${BASH_REMATCH[1]}"
  echo "Release major ${tag}"
elif [[ $1 == refs/heads/master ]]
then
  tag=latest
  echo "Release latest"
else
  echo "No release to do for $1"
fi
if [[ -n "${tag}" ]]
then
  summon --yaml '
    USER: !var gs/ci/dockerhub/username
    PASS: !var gs/ci/dockerhub/password
  ' bash -c 'docker login --username=${USER} --password=${PASS}'
  summon --yaml '
    USER: !var gs/ci/github/username
    PASS: !var gs/ci/github/token/gopass
  ' bash -c 'docker login ghcr.io --username=${USER} --password=${PASS}'
  if [[ "${tag}" != "latest" ]]
  then
    docker tag camptocamp/c2cwsgiutils camptocamp/c2cwsgiutils:${tag}
    docker tag camptocamp/c2cwsgiutils ghcr.io/camptocamp/c2cwsgiutils:${tag}
  fi
  docker push camptocamp/c2cwsgiutils:${tag}
  docker push ghcr.io/camptocamp/c2cwsgiutils:${tag}

  if [[ $1 == refs/heads/master ]]
  then
    docker push camptocamp/c2cwsgiutils-redis-sentinel:5
    docker tag camptocamp/c2cwsgiutils-redis-sentinel:5 ghcr.io/camptocamp/c2cwsgiutils-redis-sentinel:5
    docker push ghcr.io/camptocamp/c2cwsgiutils-redis-sentinel:5
  fi

  rm -rf ~/.docker*  # Docker logout
fi
