---
name: Audit

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  audit:
    runs-on: ubuntu-20.04
    name: Audit
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        branch:
          - release_2
          - release_3
          - release_4
          - '5.0'
          - master

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: asdf-vm/actions/install@v1
        with:
          tool_versions: python 3.8.0

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Audit
        run: c2cciutils-audit --branch=${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
