name: Rebuild

on:
  schedule:
    - cron: "30 2 * * *"

env:
  IN_CI: '1'
  SUMMON_PROVIDER: /usr/local/bin/gopass

jobs:
  rebuild:
    runs-on: ubuntu-18.04
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        branch:
          - release_3
          - release_4

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GITHUB_GOPASS_CI_TOKEN}}

      - name: Pull
        run: make pull

      - name: Build
        run: make build

      - name: Acceptance
        run: make acceptance

      - name: mypy
        run: make mypy

      - name: install GDAL
        run: docker run --rm camptocamp/c2cwsgiutils:latest-full /opt/c2cwsgiutils/install_gdal.sh

      - name: Release
        run: |
          summon --yaml '
            USER: !var gs/ci/dockerhub/username
            PASS: !var gs/ci/dockerhub/password
          ' bash -c 'docker login -u $USER -p $PASS'

          for tag_suffix in "-lite" "" "-full"
          do
            docker tag camptocamp/c2cwsgiutils:latest${tag_suffix} camptocamp/c2cwsgiutils:${{ matrix.branch }}${tag_suffix}
            docker push camptocamp/c2cwsgiutils:${{ matrix.branch }}${tag_suffix}
          done
