---
name: Rebuild 234

on:
  schedule:
    - cron: '30 2 * * *'

env:
  IN_CI: '1'

jobs:
  rebuild:
    name: Rebuild 234
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        branch:
          - release_2
          - release_3
          - release_4

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker

      - name: Pull
        run: make pull

      - name: Build
        run: make build

      - name: Acceptance
        run: make acceptance

      - name: Release
        run: scripts/publish ${{github.ref}}
